apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: samba-storage
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/samba
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
