apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homarr-apps
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/homarr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system