apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-data-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
        - name: homarr
          image: ghcr.io/homarr-labs/homarr:latest
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          ports:
            - containerPort: 7575
              name: http
          env:
            - name: SECRET_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: homarr-secret
                  key: SECRET_ENCRYPTION_KEY
          volumeMounts:
            - name: homarr-storage
              mountPath: /appdata
      volumes:
        - name: homarr-storage
          persistentVolumeClaim:
            claimName: homarr-data-pvc
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: homarr-web-svc
  namespace: monitoring
  uid: 8d5e8a3c-8d45-4656-9d9b-30929d2b91a3
  resourceVersion: "142887"
  creationTimestamp: 2026-07-15T17:06:55Z
spec:
  ports:
    - name: http
      protocol: TCP
      port: 7575
      targetPort: 7575
  selector:
    app: homarr
  clusterIP: 10.43.234.16
  clusterIPs:
    - 10.43.234.16
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
status:
  loadBalancer: {}
