apiVersion: v1
kind: Secret
metadata:
    name: cf-api-key
    namespace: games
type: Opaque
stringData:
    CF_API_KEY: ENC[AES256_GCM,data:7xcrBpwhvwarNuue69e67X5Je/dsFZLJ4pzQGaC8pZl5xAXB7PnVrRAHvIoB1IdUQcN3dxVTzNEv9qfd,iv:k9jW3EZeFRVIC7fhTWUpRfHMhVaHROuaO6NMQGv+yOA=,tag:EBIU8q85i0NpCA1iBskkGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmczR0ai9CSGRaZXZ6dW1s
            bkZjaGpJelhld2grT2c5OTg0Snk3aGkzRVFzCmhUMFh0end4Zy83a281UjRRdWFa
            Z0RVOUM5WEJ5ZGZUeFpLajlKTnlOT3MKLS0tIGM4Z250Z1NIVnlPVkJWcTRvTk91
            cEZ4K3ZLN1hRUnU2b3kzZitjaWt5bDQKBxOY4UxFl6iRpRBVmqbaBpXpqaPcuKlm
            RwuIy0Yl7g5VfX3ATlpm/pg/FcPe/cYRzLAeNTe2244opMKz0dHmjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180054056hudrzph9dyz0kev4sacz9nfas84fc3aluyj5xhlsxv7sdsfe02
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T15:01:47Z"
    mac: ENC[AES256_GCM,data:UI4rbYf4vW7h718b+pUbhaeQ9H3Kv47uKPhBBdwpCZOwEzSqeD48QkbMOIvQnhQhFDkWZujEFV1rBGMBhvBxoumBuT6e5DSNW6Imaedt1Z1LuxBG0PXMeA95ZWRyRHf37zAZWtrIYIaCPpKkiJb/P4QpiJnPpcrn57kueOzfQgw=,iv:K17loMPZ8jZlH+OITWeIOwNAuoBwirkRJ5Rglq33PP8=,tag:akaYQ9ip3wEcJXVMMRZwOQ==,type:str]
    version: 3.13.2
