apiVersion: v1
kind: Secret
metadata:
    name: cf-api-key
    namespace: games
type: Opaque
stringData:
    CF_API_KEY: ENC[AES256_GCM,data:Qut09EuZ8QuJ9y3RGyJhPj9db8D0U7kXIO82mLbn1Ne45PdYVE+N+d4FvOlNNPrjYVthq/v4kTEFxfZD,iv:Pyim7U6VUmzOz8fgz3A1/ximWeJIfQYpMq59osJhzP4=,tag:+3zqrMpEhD+ZRP4U/g0GXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbGZtWWphWVg5dFNER3V6
            VzEwYlhtMU0rRk9JY2JJSngrTFA0bTNtRVgwCkJrODRaTkhRYWExUGlYaS9hRGJs
            MGVYSndPN0dKNEE1bmhYRExBSjVNd2cKLS0tIDBPZXN4QzJGWnpHMGR1YzdTOVNq
            TjE3R3d4U1B1ZkM0dUdRdEZwT1N6S00KA0KMbJUUTOawCTyb+Cde3g2gTL5W+op0
            UXrEkOJle9ndywvN19bNqalq/MaD7iAhTYaGD+baWVk3TGpe5aOHZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180054056hudrzph9dyz0kev4sacz9nfas84fc3aluyj5xhlsxv7sdsfe02
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T14:37:10Z"
    mac: ENC[AES256_GCM,data:bNiL0K97l7ZCZsK6LvJyqymH7lL45Vf21s8d0hCr+5PwR4Ch3wP1M+9NJNI8vB4RqCJphKx38kyTySyn8oOtRxQH0POELu69MjBxIhC7TS1HcKpqJ2bmQau6yM2fTiJOlZPZiAURF4ZlZOOg3SPRUhrUgSKwpazhMD4eykBlGl0=,iv:Xy5DvGfDdIMQ+QsP4FA7Se46B5l2AfYztlJjEEw39BU=,tag:43jIpJpcljwDIrTfzRjPg==,type:str]
    version: 3.13.2
