apiVersion: v1
kind: Secret
metadata:
    name: minecraft-secret
    namespace: games
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:zLFZ5X6oLZywbngqpRBZ1Wl6slk9fXCppNQHntmTAQXstaYf75US9qNBtMoFf4usJVRduuSCUiRhTh3zuJF+AQ==,iv:kvVMQTzFdeoBt5ooLOYOZvMwCgFmib0kBY4tCOxqkos=,tag:n9YvQGgsVw+afsmavomuvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcTlkZXZwL1Vmb1FjZW1k
            VG8zZWhsb0xXbmcvMzUvV2xVaEhGSnpkdnlrCi9GQ015cnN1ZU54WW91b1l1a09B
            RzUwYVNEMmhPK1dWa0xnM2R1SzkzUnMKLS0tIGJZQWRYQ3pKcnBZaFY2a1NaZEIw
            UGFqaWMrZXFrd2lkRzlMeS93U00vT1kK7Vo8zCcRNkrMpTyImS6PJb0/vkUVqenD
            yfm+P3nK8zp+Dx07sYj5/TL3YRgx2lT+q82AAy0IvhU+Cnuk9qKTYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180054056hudrzph9dyz0kev4sacz9nfas84fc3aluyj5xhlsxv7sdsfe02
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T02:17:40Z"
    mac: ENC[AES256_GCM,data:ydPY9v4v6l07+v0r8GALwMXdN+xPbBjljr7DWaHg6AzqrY7FGiEH2kb/HWiMwCSshFul5V5j6A98Is1k6HPOprkkYK+V5h/MgeiCxgHtNypaAY+kpluo+uC4jej0hkzqgQgjDiPH3hZ3oUW4LOzXq1vVUOIGSGNnhTQXlcadwDc=,iv:IlY9/yK8C60n3FFwFbzUK+gx4GZb76ZyjAC7h1tYkqc=,tag:UwOSgFMSDD6AutDRXDaw4A==,type:str]
    version: 3.13.3
