apiVersion: v1
kind: Secret
metadata:
    name: minecraft-secret
    namespace: games
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:63LvhIOyf9jv1Of0YOR0OyeOHl5Vi7xqPJMcG8+6Bma5R0zusrrrqBPdRRmdn5YbkGVW8YJjqgIYkbS7rDbtrw==,iv:oiga9RQAgxhfY4E5+wpDvlN0fWZSnNJOOX/ghgPQMzQ=,tag:eTEYcVf+B9p3gKE2n3/VpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTzgvWVZQK2ZiMGxoYWNw
            T00xeEFzb3N5RnBXS0ZST2RESFhYemo0UkhzCjRoWnFpZlVuTnJXUW9ROGIwU25i
            Q1A1T25OSk91TzhLaUR2cWZYbng0UzgKLS0tIFlIOGtFTkZYMnoweEJwdTBwUnl5
            N0RjT24yc0lkSnl0b1d5NkhUU2JEUjgKGOsUHUMZS0Q9jRQIDfOybCseQWgL3bRL
            NloXOWprfov8FsRj8dbni95YHJaRH0A5JOfgq5PiK1daBzbgyXCCcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180054056hudrzph9dyz0kev4sacz9nfas84fc3aluyj5xhlsxv7sdsfe02
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T17:37:32Z"
    mac: ENC[AES256_GCM,data:1yOrjmaIRFkBUDRL/Ckb2xpbMf4i/cDvRPiWvXNBYg2Yheg5aW8y1Zk3WogC083/sprNEpRsPQuM2+bNRuRyozIztCUyaoW/4RaL1k19CZVEeNbG6a7+2J8CTKu1gXxxfLjHHZ4qFhBkd8k+VH5d7R4tB9ZwdhoDCEr4PzD2ed0=,iv:+HqtAW5IK33K5nn6YP7wuHuFqyXMMftzIqVvqJAcrRI=,tag:OuwJXSAAj2Kh2YVrKMIHxQ==,type:str]
    version: 3.13.2
