apiVersion: v1
kind: Secret
metadata:
    name: samba-secret
    namespace: storage
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:2+FTHkjAae/nunD3I51p/F62U5Jnu8CJPRXfIjfX,iv:ZXjAEiGVSdudYXcif5SC2wbFSkpdeb2Iy1tGjt9tV54=,tag:5RZv8ebIZ6HgkCun9bIJKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWd1JMcmxCZFN4T2piWU13
            MXdNbk9MZzlselBrNkNNSjhMZ2NUWnRiMEdvCjhsenNIa0ZzaEFXeDZKbUJaaElO
            WHB4VXNmRFNJN0ZlMlNxMTY0NVhkQlkKLS0tIFJ3M0x3emdNcURKaVVJRW85bUlF
            RXZuOWZUVm1FR3c0alBKWEhYZUpXTjgKq5kMvS+eJaLt8nvjwCRGObeP+ty/jXVU
            vA0r8ImqY8tP4vLIRtGOwz+IWwF+XAn2TO+rn2VbT6rjEzH4pz17aQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180054056hudrzph9dyz0kev4sacz9nfas84fc3aluyj5xhlsxv7sdsfe02
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T04:01:25Z"
    mac: ENC[AES256_GCM,data:TNcdV/M1nqzqTFhqOwWZ+G67F5pTpM8mM5IL7N4D8HVB2sNc9A6uD1BfY7bWxGX16ByBvbq6HTcjkn8GBAjxJsjajrI/lC9UGzL68pHKZQVL5W0AzEoi8CXm5htvl0AoccNFKudiQmAEmRGumL5e98KWU3uBghZEorTiIRri+gw=,iv:jguNap+rCF1fyfpUjGzRZJynPLSwB4FBmWCk2Rap9VY=,tag:aldS5QxQe5Ir/SkuT8eyuA==,type:str]
    version: 3.13.2
