apiVersion: v1
kind: Secret
metadata:
    name: samba-secret
    namespace: storage
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:BmG3Z1t5Q0/v57Ei8qXwBZGc1yXmrWEkRS7L4Q46V8+amHKh1MXJDGztxG/t70Q+GUq11hrqEznWvS4=,iv:RRy98faMoFNsSnNPJ4h+rpklpidKROV/iGSgKzHAFaU=,tag:SLmRqjyMzPqh9T9PBbZsFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWXJBMUdvSFBoRVJvVG14
            ZVNuSlJRMXdIbU13MUV1dE9SMW0vL2JMK3hZCndwWmF0d3NWaTRaZkFSQUxPenJC
            QWhxQUlLUmU0T0dnQ29SdG50dXc1UHcKLS0tIHlybnJNWGZpSTlGNHkzYllMWXQ5
            NDNhMnlyOVRFbk5vS2JlV3A5TmdqYTQKbS+x2gj7V8EqwShji2EBnqZC0JeejSc0
            iGzLzCZ+wyBAj7lL0IOrTTv2jlLd2bP/IGMvX07vm9Id27alx3IS/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180054056hudrzph9dyz0kev4sacz9nfas84fc3aluyj5xhlsxv7sdsfe02
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T03:57:16Z"
    mac: ENC[AES256_GCM,data:w62wVWedMvmMtUqa/Cq4oUGda5T4zaronuTWNX0pD6PVgObPC8FEgAQ3lYh79jwU0/EYclioaPl5OEkk9cPBFXJqpzfAkLjLpppDxnfynDToxx7oIWsGK9qJVUOs9IvZKIT9/V5/v3mWhJ+QRZVmPH4hMuRQJpbjhWrnjpQ2i68=,iv:rSZ1zJ9dWwQNlzw0rJJEASxADlqdiUNRgsOL0H99poI=,tag:M54eQw3Uc0FEo7JYpZPv7A==,type:str]
    version: 3.13.2
