apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      nodeSelector:
        kubernetes.io/hostname: homelab-worker1  # <-- Target the worker node
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:10.11.11
          env:
            - name: TZ
              value: "Asia/Kuala_Lumpur"
          ports:
            - containerPort: 8096
              name: http
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
            - name: jellyfin-media
              mountPath: /media
            - name: tmp
              mountPath: /tmp
            - name: dri
              mountPath: /dev/dri
      volumes:
        - name: jellyfin-config
          hostPath:
            path: /mnt/sata-storage/HDD2-share/jellyfin
            type: DirectoryOrCreate
        - name: jellyfin-media
          hostPath:
            path: /mnt/sata-storage/HDD2-share/jellyfin
            type: Directory
        - name: tmp
          emptyDir:
            medium: Memory
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc
  namespace: media
spec:
  ports:
    - name: http
      port: 8096
      targetPort: 8096
  selector:
    app: jellyfin
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  namespace: media
spec:
  ingressClassName: traefik
  rules:
    - host: jellyfin.zieqs.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin-svc
                port:
                  number: 8096