apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-backup-secret
    namespace: vaultwarden
type: Opaque
stringData:
    restic-password: ENC[AES256_GCM,data:AU3uJssTQIEuz04f22Bl79wIk0yj4E45TiJ7dmyBrhaPsvdEDGZ0Aq8vXXI=,iv:1wikE3G7jN/Le0OASKV7EgU1OKECowjEKQedzi7FAHc=,tag:5IXEvSucVKwNXZAk1IiF+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQ3FnWmVKOG9zS1RCenZ4
            a1RvcEduQnJ3RXZzR3YrbHphamR6VWIraDBFClpRcVd2UkFqVnJsSkM3bkhYRGNq
            SVMzMnYyaTJPK0l4OVZLMHc5dTkyeGsKLS0tIE9GN3lKQVhUeDdIOGZoc0R1dElS
            UnhXVDBJM3M0YjNHSmd5OWhXbHd5SHMK7m2QdgN/bKFwmDBm7ZqTar2zZCRtUIwH
            K3hISLV/bKCWzxV5LH4GT2Bkm4wYdmxMQ9dSGWxz3d8btbjE6dBwJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180054056hudrzph9dyz0kev4sacz9nfas84fc3aluyj5xhlsxv7sdsfe02
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T02:34:37Z"
    mac: ENC[AES256_GCM,data:CGP4zjj1uI1TqPhv9gUskkE7WhrxGMze6GMd4Yi1NTeQqQaxBRpgLtVByIkh2wjioZH+P6WuxVk9uyYoNukz5bB33kx04uPmTHKzlVfB6vM8dUdD23rpFbZ7Ci/weIT0GQG2cXDEJe0I/lFLfoMWHFf8Ae4kn/rZYy5E5IZQvXs=,iv:JJzXn5ElqX4zGerU5k/fRmYwALOLAeAzTTJ9B5nu1D0=,tag:sVtLO+MbMphEji1HUxMpJQ==,type:str]
    version: 3.13.2
