apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data-pvc
  namespace: obsidian
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
  namespace: obsidian
  labels:
    app: couchdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 5984
        runAsGroup: 5984
        fsGroup: 5984
      containers:
        - name: couchdb
          image: couchdb:3.4.2
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          env:
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: couchdb-secret
                  key: COUCHDB_USER
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb-secret
                  key: COUCHDB_PASSWORD
          ports:
            - containerPort: 5984
              name: couchdb-port
          volumeMounts:
            - name: couchdb-storage
              mountPath: /opt/couchdb/data
      volumes:
        - name: couchdb-storage
          persistentVolumeClaim:
            claimName: couchdb-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb-svc
  namespace: obsidian
spec:
  type: ClusterIP
  ports:
    - port: 5984
      targetPort: 5984
  selector:
    app: couchdb