apiVersion: v1
kind: Secret
metadata:
    name: homarr-secret
    namespace: monitoring
type: Opaque
stringData:
    SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:nvyWgA56xa4YUv0j23zxhGt1aIoMz18/tIfOyX9jzvHPAs2OnI+8ZxBpTXC4B8C/nrquTbbxnB7XM3eLqqgoAA==,iv:tJHi0l+f1VvZX4vYTdhMfY+/FGfqW3F4brqr6qPLfwU=,tag:mDqaLPdhwVhAidbw1lTqKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMmUvcDBsaEdvTGVaRTVP
            Rnl5OXo0UzM3blRtTWFnY0JoMk5hbHl0NlNrCkV2QzYrdHhMUmhEZmQxeWNWOFZ3
            b0pYMC9tenk2cWprWit1eHN1TngwdnMKLS0tIFdvVmhjMVJaWjV6ZmR0bkpxZkFE
            djZna2Z5Nk9DSDU3RUxlOFIvLytsU2MKLOGosX9Vc1eBCEb7XsQ2xcWg7hsQYXS7
            0cefOuX6HIBWi9OQ3GQX2Jq7eEZ73HmPAmY4H9NMM3Hr33UxCQiyIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180054056hudrzph9dyz0kev4sacz9nfas84fc3aluyj5xhlsxv7sdsfe02
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T16:34:50Z"
    mac: ENC[AES256_GCM,data:xMQJiLlKGeE6WJgmeXzkfPuUcHNMHrFRw3SVyXzyYpcYsZqa2eQGEB4ISuV3F48WzQmhQ7lc16PJ5kuuNnpeGCIFfNJ+L7vm7iwQ9RNrXVmCLk47gTGL75EjE8dcROqQhx/R75tZ8TfJPLgKkSwkDhMGATfpo5LskG3frjaNwU0=,iv:NMxVDvS1e3Jifa2954Sqq883HcYFDIxOQIouEHU3v2c=,tag:hi4ltK0W2LqS0XKrLZYY2g==,type:str]
    version: 3.13.2
