apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: networking
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:sqLg2Do=,iv:PiNK5ASFuqyFr9JuM7lfEj+r6WtYBHLqLsUZuhm0kSg=,tag:3a+kDhEZ9cV0demF+ZwZVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMVdyaUpuQTZzRlF6YUM0
            THJZQVNINXJyYktyS1doUVcwYllQb3VTeXdVCkx3a3JBOWRERWVhWitGQ1RmM1JE
            TzJXemZTYUxNN0VJYWJKenVDZFdZOFEKLS0tIEtqaFN2WDBrY21QY0E1S1lHQjB3
            ZmFnZ1cwQjNUeGpnZEVDc3ZRZHhJYTgKPzixyNPEFxGvz1SPXMOkxRMAGEGri+SA
            wcRmSt7/jpBTONYBHwPsIgcbEQXmCU9nGfn3WBgqWFAnNMtuxUWZ9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180054056hudrzph9dyz0kev4sacz9nfas84fc3aluyj5xhlsxv7sdsfe02
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T16:34:49Z"
    mac: ENC[AES256_GCM,data:8bw8jM2kLcV9Bum4Ddjq4ee5LuPXmTGeUY+5HZWn3krTXCdUhedak//iLEJqjs93rt0xEVO0kr1F9kB27avaFrrnb5VSlDqt3jIDuOmAyW6k3B7i3YX5FXO80tL7P/oaNGfUVEE7xoHIHEh9y70heMiKOs3HxM4nlbwnb58O0bQ=,iv:aZkDUlse+seQ38c0lwSg7fBF2Z+asBtsz6BKB+V+1mU=,tag:LC+qgHNYtKZf8GP+J3fHyw==,type:str]
    version: 3.13.2
