apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-central
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-central
  template:
    metadata:
      labels:
        app: cloudflared-central
    spec:
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          command: ["cloudflared", "tunnel", "--no-autoupdate", "run", "--token", "eyJhIjoiNDVhM2RkYTcyNGFhOTk5MzE1NzI2OTY5NDJhNzhkYjQiLCJ0IjoiZThjNjNlYjktYjg3NC00MzYxLTg0ZjEtNjM4NzIwMzY0NjRjIiwicyI6IllUZGtOMll6WW1JdFlUQTVOeTAwT0dFMUxUaGhNall0TURneE9UTXdNR1ptTVRKayJ9"]