apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-central
  namespace: networking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-central
  template:
    metadata:
      labels:
        app: cloudflared-central
    spec:
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2026.8.3
          command: ["cloudflared", "tunnel", "--no-autoupdate", "run", "--token", "$(CLOUDFLARED_TOKEN)"]
          env:
            - name: CLOUDFLARED_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-secret
                  key: token
