apiVersion: v1
kind: Secret
metadata:
    name: couchdb-secret
    namespace: obsidian
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:S/Ruh1o=,iv:z/3Aa9OoL4wSmX9KvPIyzQsjUY3QCWSB4/iHvQDaaPc=,tag:E/V2cGz1YFaDOqe5UBlp4A==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:8a0U/Q4=,iv:PW2cOCI2gATj5LB9RrhRLg9YDMsMMQMp6R7zeJELdW8=,tag:GW1ISskFgCAAeEhpM5ItZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aTk0ZnkzVFAvYXBuNzJz
            WnBaNnRCQWcrVWFFMGRlTy9YUDdQeWdRWjA4CmpuWEZlaDJBRGxOS2c2Sy84SVdp
            SWQ0eCt4YnNiMlBkZlVSZ29kZSt6emMKLS0tIG9XOExTYmZENjBuYURMc0FWdUwx
            TGxmT2V4TjNQSjVqcGROdXc1Vm0rZkkKHe7wxyjRRq3M229eGq1FFlq2HoUxtpo1
            ydwqmW4Ayx8ZTgtMyEZmJiNBwwjzt8O5HygdZUMl4noLy3ZBh+KuFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180054056hudrzph9dyz0kev4sacz9nfas84fc3aluyj5xhlsxv7sdsfe02
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T16:34:50Z"
    mac: ENC[AES256_GCM,data:24uHMPFUxjU3Ib/KNgyPoZOD/EfAposh9yrio38tjJ4q/fa4Sqxn2LZ3Vri9bB2DT6wSNwPf8iGUIW2noL8zBxQxp9sExcYke8eHHV42msoKVwsDgoqyV0DnDZ1ddn28EwXM6wJk+SpQs7O2fAuodvDirmpiAfuuiVjgOPM0eJI=,iv:FXqwa1uH3jipOJM4aHx2zDGymCDpyuvzM0o2pDy7H2E=,tag:/YMB77CO21kwFoBnn+7fmA==,type:str]
    version: 3.13.2
