apiVersion: v1
kind: Service
metadata:
  name: ts-pihole-dns
  namespace: networking 
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "cluster-pihole-dns"
spec:
  selector:
    app: pihole 
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP