apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: networking
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:8voPchRzUg==,iv:Xo6UnEDqxD02S0iBcUVfocK27mQp3oG90w8c463Q85Y=,tag:80wYUKv42DKiMrsMVxEP8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VUR6MnJleWVtNU5tdERo
            cXRpTnBMWGswQjBEb0VybGxnWVlaWWdoU3lRCkNqYmJIb09PdHQvNmtnM3Z3Kzcy
            WXpSSHlMRkQ0T2x3OWlsRUJRZ3dSVEkKLS0tIHBGRHZmNjQ3RG9KNXdvUlQ5b1F2
            NEdJdXFjOXkwSG9zeHRmbkZ0Q2xiT3cKHvmOkRa1GzMG38e6raArKtDxftp6N7LK
            4l+aMOvpgK3fMhs+EUhTeQDDW9t6GdSe63YUNINEN0aHtEKHtsoXuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13fgxz3eta2se0h4thrhnnda09kwth5333wllqldr83zdc9xxz5pqn7lmdr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T13:15:29Z"
    mac: ENC[AES256_GCM,data:oTtc78MFDEQpFbqJl3OSVGMPgD80DyaFtrEritd00T/Zrci8JvYaIobK+uY+SW6DfI80lW9UJMWaVseUcT0rpUz/kYHMTz76JwNnIzUUXAQ5ZnHNI2bMwp3ShWsoxr1/vtJATi7CO1QEtKhMcE48rSuCa4AjkD5Ec/D98NWJEfA=,iv:qvG876uQM7poXIXmG0IxFoXlylgzJGYPjEEKMcK7xj4=,tag:Znw+a69cMsrXQpFlnhg3jw==,type:str]
    version: 3.13.2
