apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: networking
spec:
  releaseName: pihole
  chart:
    spec:
      chart: pihole
      version: ">= 2.14.0"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: networking
      interval: 1h
  interval: 1h
  values:
    # ----------------------------------------------------
    # Storage Configuration
    # ----------------------------------------------------
    persistentVolumeClaim:
      enabled: true            
      size: 5Gi                
      storageClass: "local-path" 
      
    # ----------------------------------------------------
    # DNS Traffic Configuration (Exposed to your LAN)
    # ----------------------------------------------------
    serviceDns:
      type: LoadBalancer # Changed from ClusterIP so external devices can use it

    # ----------------------------------------------------
    # Admin Web Interface Configuration (Correctly Nested)
    # ----------------------------------------------------
    admin:
      enabled: true
      password: "homelab"