apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:C7i7xAoR+mI8asSlzgPlEpZG32XwKGQNudoLehGo/VfTneCL6yQpSzR2oai6QC97ONZ+KPYBg17p2WculfM+ZP4Dou762m5EeM56cRc+sjU4jRlzcsDKLY6PY1LyfZsuyMVLXEu/t/m5tyBG9YKeQBxN+JP9WEDNzBqrouVdYsU8ZGtO0wLb2bGVdK5vyC/fYNj4NNPw+LmdgNZmL3zNUbra74N5PW2KVwVcBbbxaRRXPKzakc2h420m5DxTl6Bxk5/2yiJM5h5q/nJ2cL4PrB0z0Kf9ceOAOz0Ogy9fORxxTaI+JkSWdFd2ELtsb0A4vfjj5KnaxV4=,iv:T4KCAP5IZFlI1of2p/qMzQVBrLXSl6Q8+Nq3bt33Gvo=,tag:2jBaDqXgJqz6JXUVbSYaoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TjlxdEthZWRRcGhkZko1
            UXR5Mm9ILzR3c0xUcnEyT2duMnd5aVczdGdrCjdlRFBYMCttVnNqUllQM1hrQ1FS
            UEs1aFNBYTI4Y0NIQzAyV1NVbXhaQ3cKLS0tIDRtKzhlOCsvNjBKaGVZM3dya2w1
            YXJ2blFpc3M4OUU3djFCUmpwUUlhbWsKwj2pxdEdsmhpnTENVyGDgdHVzwQtx6lz
            PxrVN38lqWLs7UFyqz2qBUmBy7Ns0LcBywf6v0n7jVgIudqEKqH7Xw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180054056hudrzph9dyz0kev4sacz9nfas84fc3aluyj5xhlsxv7sdsfe02
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T02:17:45Z"
    mac: ENC[AES256_GCM,data:avahtWe8G0gmlQgp08k3/fxtqr+FmA3gWdlaWMqkI/YdeBakW3k4hQj2Z/8/blvYaHRDR3vI5JL8BbViLrvqb6kk3oxCCTMGy8u5hlUWEvhuQQ6mMRwOSpavfStvPskFq8o+8BqFVtS4u2YYMeJSsyKI7sLoOhgGq1ttlpR8Tyk=,iv:4y+L1SophwNBL6kOS4FTBKkitvXr4wCE9Z01o2nbaOE=,tag:Bw//T1ZrmR2C/yJN1fqOlQ==,type:str]
    version: 3.13.3
