apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: kube-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Rqo8yAEEF/fmhJwHkGa59jMIYOg1kDNsOId05wIuN7vYArHNBHvZMFqKMmdP58IK8HGA33C81Uo9gZZJnLuR0CYzvXOxHLJ1SzBlFQpjRGPxYqrCQ6H9G8ehAG7FqTKrADLnTDozFcOBGHhFgagh/a9oMS2I5JKI9LV/yzsmdLVd40t56MEucXRGf3YDs1XEgoQvb2xT/koBmwgsclw33IkMQ/pxRbpN4qf4GFeahMnV18DPFV3jbiCyJFjSpynhMAh6PnKg90b+/c6lj8Ej69Sz0y4vxmuEZDfT41VQlcwKLzD4SPrcV8hcCSUlV1gAG69FCleVWb8=,iv:yZ12HKRw/DQRRkGfL0lR0E7Va04vo1QV0D+kJjZB9RE=,tag:vN97QfNry1vjCOf3s8NUOA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeldYWlAwNTVXcjZSVWxV
            TUZHakJMVVBTMWRsZExrWmYrT0hZcXBzendNCkMrTHRaZzJ4NGpwcExCcHVSbFh3
            ZjZoZzQ4ellVNjV1bXVGaUMyWmpCUEUKLS0tIFB1QjFPRG1iekFxVDYxaS9JKytC
            RE5vcEZIQUtxVUFmRVR6YjFBS1YreWcKfzpUUaTpGaH/BabGub19P75SKBqHiIA4
            qDklXW9jBVh47Oio93nQhzaZF7J2I/7byS52cyB2vErSWJapNB0/6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180054056hudrzph9dyz0kev4sacz9nfas84fc3aluyj5xhlsxv7sdsfe02
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T16:34:51Z"
    mac: ENC[AES256_GCM,data:3Buu/7tej4M/6exhYetYtKUd5sQfCCJOJV7pPWDouAqX70dqf7lH8gomfHGb5HYsPCLPkuU+XGs5ihD8oqoTkN1C/+Su3Ao/wbbTk8gZp3mLHW34dP4n/uREeUxqi/o5ugSQ38AQyFJEJOA9QbxCghCReEdQWFtBCzhTOuRmRAI=,iv:8x5Gno2I6fvpRVoCRlcQufcVNqsNkeEjpNVHUFvc04A=,tag:boGjOJp67GdO7OEdb3wfRw==,type:str]
    version: 3.13.2
