apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: games
spec:
  replicas: 0
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/hostname: homelab-worker1
      containers:
        - name: minecraft
          image: itzg/minecraft-server:java21
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          tty: true
          stdin: true
          ports:
            - containerPort: 25565
              name: mc-port
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "NEOFORGE"
            - name: VERSION
              value: "1.21.1"
            - name: MEMORY
              value: "8G"
            - name: USE_AIKAR_FLAGS
              value: "true"
            - name: ENABLE_COMMAND_BLOCK
              value: "true"
            - name: ONLINE_MODE
              value: "false"
            - name: TZ
              value: "Asia/Kuala_Lumpur"
          resources:
            requests:
              memory: "8Gi"
              cpu: "2000m"
            limits:
              memory: "10Gi"
              cpu: "4000m"
          volumeMounts:
            - name: mc-data
              mountPath: /data
        - name: playit-agent
          image: ghcr.io/playit-cloud/playit-agent:1.0
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minecraft-secret
                  key: SECRET_KEY
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: mc-data
          hostPath:
            path: /mnt/sata-storage/minecraft-data
            type: DirectoryOrCreate
