apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: games
resources:
  - namespace.yaml
  - deployment.yaml
  - networking.yaml
  - secrets/minecraft-secret.enc.yaml
  - secrets/cf-api-key.enc.yaml
