apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: games
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      nodeSelector:
        kubernetes.io/hostname: homelab-worker1
      containers:
        # Container 1: Minecraft Server
        - name: minecraft
          image: itzg/minecraft-server:java21
          tty: true
          stdin: true
          ports:
            - containerPort: 25565
              name: mc-port
          env:
            - name: EULA
              value: "TRUE"
            
            - name: TYPE
              value: "AUTO_CURSEFORGE"
            - name: CF_SLUG
              value: "create-ultimate-selection-2"
            
            # Pointing directly to the file copied into /data
            - name: CF_MODPACK_ZIP
              value: "/data/modpack.zip"

            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cf-api-key
                  key: CF_API_KEY
            
            - name: MEMORY
              value: "8G"
            - name: USE_AIKAR_FLAGS
              value: "true"
            - name: ENABLE_COMMAND_BLOCK
              value: "true"
            - name: ONLINE_MODE
              value: "false"
            - name: TZ
              value: "Asia/Kuala_Lumpur"
          resources:
            requests:
              memory: "8Gi"
              cpu: "2000m"
            limits:
              memory: "10Gi"
              cpu: "4000m"
          volumeMounts:
            - name: mc-data
              mountPath: /data

        # Container 2: Playit.gg Tunnel Sidecar
        - name: playit-agent
          image: ghcr.io/playit-cloud/playit-agent:0.17
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minecraft-secret
                  key: SECRET_KEY
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"

      volumes:
        - name: mc-data
          hostPath:
            path: /mnt/sata-storage/minecraft-data
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-svc
  namespace: games
spec:
  type: NodePort
  ports:
    - port: 25565
      targetPort: 25565
      nodePort: 30565
      name: mc-port
  selector:
    app: minecraft