apiVersion: v1
kind: Service
metadata:
  name: minecraft-svc
  namespace: games
spec:
  type: NodePort
  ports:
    - port: 25565
      targetPort: 25565
      nodePort: 30565
      name: mc-port
  selector:
    app: minecraft
